### ISSUE TITLE
testsuite fails to build with scotty-0.30

### ISSUE THREAD

**Issue by juhp** [Helkafen/wai-metrics#4]
```
       Building test suite 'metrics-test' for wai-middleware-metrics-0.2.4...                                                       
       [1 of 2] Compiling Network.Wai.Metrics                                                                                       
       [2 of 2] Compiling Main                                                                                                      
       /home/curators/work/unpack-dir/unpacked/wai-middleware-metrics-0.2.4-99366b831109417cd8e739fb45e9fd214cb79f28a507f8154e552812
0042d0ac/tests.hs:16:70: error: [GHC-61689]                                                                                         
           Module ‘Web.Scotty’ does not export ‘raise’.
          |                                                       
       16 | import           Web.Scotty                  (get, html, middleware, raise,                                             
          |                                                                      ^^^^^
```
